// Generated by CoffeeScript 1.6.3
var ajax, array, generate, getTldList, post, request, show;

request = require('request');

array = [];

show = function(req, res) {
  var whenDone;
  whenDone = function(array) {
    return res.render('tld', {
      tlds: array
    });
  };
  return getTldList(req, res, whenDone);
};

generate = function(req, res, whenDone) {
  var idx, phrase, result, str, tld, _i, _len;
  if (array.length === 0) {
    getTldList(req, res);
  }
  phrase = req.body.phrase;
  console.log(req.body);
  phrase = phrase.replace(/\s+/g, '');
  console.log(phrase);
  if (phrase) {
    result = [];
    if (array.length > 0) {
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        tld = array[_i];
        idx = 0;
        while (idx >= 0) {
          idx = phrase.indexOf(tld, idx);
          if (idx >= 0) {
            str = phrase.substring(0, idx) + ("." + tld + "/") + phrase.substring(idx + tld.length);
            result.push(str);
            idx += 1;
          }
        }
      }
    } else {
      getTldList(req, res);
    }
    return whenDone(result);
  }
};

ajax = function(req, res) {
  var whenDone;
  whenDone = function(result) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end(JSON.stringify(result));
  };
  return generate(req, res, whenDone);
};

post = function(req, res) {
  var result;
  result = generate(req, res);
  return res.render('tld', {
    results: result,
    tlds: array
  });
};

getTldList = function(req, res, whenDone) {
  return request('http://data.iana.org/TLD/tlds-alpha-by-domain.txt', function(err, response, body) {
    console.log('fetching tld from iana.org');
    array = body.split("\n");
    array.shift();
    array.forEach(function(tld, idx) {
      array[idx] = tld.toLowerCase();
      if (tld === "") {
        return array.splice(idx, 1);
      }
    });
    console.log('done fetching from iana.org');
    return whenDone(array);
  });
};

exports.post = post;

exports.show = show;

exports.ajax = ajax;
